/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class coretech2_local_HelloNative */

#ifndef _Included_coretech2_local_HelloNative
#define _Included_coretech2_local_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     coretech2_local_HelloNative
 * Method:    instance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_coretech2_local_HelloNative_instance
  (JNIEnv *, jobject);

/*
 * Class:     coretech2_local_HelloNative
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_coretech2_local_HelloNative_greeting__
  (JNIEnv *, jclass);

/*
 * Class:     coretech2_local_HelloNative
 * Method:    greeting
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_coretech2_local_HelloNative_greeting__J
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
