/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thread_CustomThread */

#ifndef _Included_thread_CustomThread
#define _Included_thread_CustomThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thread_CustomThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thread_CustomThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
